dataset_params:
  batch_size: 1
  split_file: null
  test_ratio: 0.05
  train_ratio: 0.75
  val_ratio: 0.2
  graph_data_path: ../20251209_cw_dataset_abacus/2_djs_graph/graph

losses_metrics:
  losses:
  - loss_weight: 1000
    metric: mae
    prediction: hamiltonian
    target: hamiltonian
  metrics:
  - metric: mae
    prediction: hamiltonian
    target: hamiltonian

optim_params:
  lr: 0.005
  lr_decay: 0.75
  lr_patience: 5
  gradient_clip_val: 0.0
  max_epochs: 10
  min_epochs: 1
  stop_patience: 3

output_nets:
  output_module: HamGNN_out
  HamGNN_out:
    ham_only: true
    ham_type: abacus
    nao_max: 13
    add_H0: true
    symmetrize: true
    calculate_band_energy: false
    num_k: 1
    band_num_control: 8
    k_path: null
    soc_switch: false
    nonlinearity_type: gate
    spin_constrained: false
    collinear_spin: false
    minMagneticMoment: 0.5

profiler_params:
  progress_bar_refresh_rat: 1
  train_dir: ./config_examples/V2.x/train_logs_fastdev

representation_nets:
  HamGNN_pre:
    cutoff: 26.0
    cutoff_func: cos
    edge_sh_normalization: component
    edge_sh_normalize: true
    irreps_edge_sh: 0e + 1o + 2e + 3o + 4e
    irreps_node_features: 64x0e+32x0o+32x1o+16x1e+8x2o+20x2e+8x3o+4x3e+4x4e
    num_layers: 3
    num_radial: 64
    num_types: 96
    rbf_func: bessel
    set_features: true
    radial_MLP: [64, 64]
    use_corr_prod: False
    correlation: 2
    num_hidden_features: 16
    use_kan: False
    radius_scale: 1.01
    build_internal_graph: False

setup:
  GNN_Net: HamGNNpre
  accelerator: null
  ignore_warnings: true
  checkpoint_path: null
  load_from_checkpoint: False
  resume: False
  num_gpus: 0
  precision: 32
  property: hamiltonian
  stage: fit
  fast_dev_run: True
  limit_train_batches: 2
  limit_val_batches: 2
  limit_test_batches: 2
  log_every_n_steps: 1
