name: hamgnn-docs
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  # 核心 Python
  - python=3.9
  
  # Sphinx 和相关插件
  - sphinx
  - sphinx_rtd_theme
  - sphinx-autodoc-typehints
  - myst-parser

  # HamGNN 核心依赖
  - numpy
  - pytorch
  - pytorch-lightning
  - torchmetrics
  - e3nn
  - pymatgen
  - easydict
  - ase
  - tqdm
  - numba
  - tensorboard
  
  # 其他 pip 依赖
  - pip
  - pip:
    - --find-links https://data.pyg.org/whl/torch-2.1.0+cpu.html
    - torch-scatter
    - torch-sparse
    - torch-cluster
    - torch-spline-conv
    - pyg
    - torch-ema
    - torch-runstats
    - lie_learn
